title: Esercitazioni quotidiane
description: Fai una modifica al giorno per districarti tra i comandi
author: Pino Volpe
email: pino.volpe@gmail.com

theme: minima

twitter_username: pinovolpe # DO NOT include the @ character, or else the build will fail!
github_username:  pinovolpe # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
